#!/bin/bash

# Created by JohnTheCoolingFan
# Distributed under the terms of the GNU General Public License v3

# This script takes an autogenerated ebuild made using `pycargoebuild` or `cargo ebuild` and
# adds necessary stuff via a package-specific script

PACKAGE_NAME=$1
INPUT_FILE=$2

case $PACKAGE_NAME in
    an-anime-game-launcher)
        (cd games-misc/an-anime-game-launcher ; ./update.sh $INPUT_FILE)
        ;;
    *)
        echo "Unknown or unimplemented package: `$PACKAGE_NAME`"
        exit 1
        ;;
esac
